import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleProvider } from "./providers/google-provider";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import store, { persistor } from "./store";
import { ReduxProvider } from "./providers/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <GoogleProvider>{children}</GoogleProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
