import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleProvider } from "./providers/google-provider";
import { ReduxProvider } from "./providers/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} bg-mainDark max-w-[100vh]`}
      >
        <ReduxProvider>
          <GoogleProvider>{children}</GoogleProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
